package com.drooldemo

import com.drooldemo.DroolsTest.Message;

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Good bye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "Good Bye"
    when
        m : Message( status == Message.GOODBYE, myMessage : message )
    then
        m.setMessage( "Good bye cruel world" );
        m.setStatus( Message.HELLO );
        update( m );
        System.out.println( myMessage );
end
