//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for airportResourcesV2 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="airportResourcesV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="departureTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureGate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalGate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="baggage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "airportResourcesV2", propOrder = { "departureTerminal", "departureGate", "arrivalTerminal",
		"arrivalGate", "baggage" })
@ToString
public class AirportResourcesV2 {

	protected String departureTerminal;
	protected String departureGate;
	protected String arrivalTerminal;
	protected String arrivalGate;
	protected String baggage;

	/**
	 * Gets the value of the departureTerminal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepartureTerminal() {
		return departureTerminal;
	}

	/**
	 * Sets the value of the departureTerminal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepartureTerminal(String value) {
		this.departureTerminal = value;
	}

	/**
	 * Gets the value of the departureGate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepartureGate() {
		return departureGate;
	}

	/**
	 * Sets the value of the departureGate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepartureGate(String value) {
		this.departureGate = value;
	}

	/**
	 * Gets the value of the arrivalTerminal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArrivalTerminal() {
		return arrivalTerminal;
	}

	/**
	 * Sets the value of the arrivalTerminal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArrivalTerminal(String value) {
		this.arrivalTerminal = value;
	}

	/**
	 * Gets the value of the arrivalGate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArrivalGate() {
		return arrivalGate;
	}

	/**
	 * Sets the value of the arrivalGate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArrivalGate(String value) {
		this.arrivalGate = value;
	}

	/**
	 * Gets the value of the baggage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBaggage() {
		return baggage;
	}

	/**
	 * Sets the value of the baggage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBaggage(String value) {
		this.baggage = value;
	}

}
