//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for flightTrackV2 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="flightTrackV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="carrier" type="{}airlineV1" minOccurs="0"/>
 *         &lt;element name="carrierFsCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tailNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirport" type="{}airportV1" minOccurs="0"/>
 *         &lt;element name="departureAirportFsCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirport" type="{}airportV1" minOccurs="0"/>
 *         &lt;element name="arrivalAirportFsCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureDate" type="{}dateInfoV2"/>
 *         &lt;element name="equipment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delayMinutes" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="bearing" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="positions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="position" type="{}positionV2" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="waypoints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="waypoint" type="{}waypointV2" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="legacyRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="irregularOperations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="irregularOperation" type="{}irregularOperationV2" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightTrackV2", propOrder = { "flightId", "carrier", "carrierFsCode", "flightNumber", "tailNumber",
		"callsign", "departureAirport", "departureAirportFsCode", "arrivalAirport", "arrivalAirportFsCode",
		"departureDate", "equipment", "delayMinutes", "bearing", "heading", "positions", "waypoints", "legacyRoute",
		"irregularOperations" })
@ToString
public class FlightTrackV2 {

	protected long flightId;
	protected AirlineV1 carrier;
	protected String carrierFsCode;
	@XmlElement(required = true)
	protected String flightNumber;
	protected String tailNumber;
	protected String callsign;
	protected AirportV1 departureAirport;
	protected String departureAirportFsCode;
	protected AirportV1 arrivalAirport;
	protected String arrivalAirportFsCode;
	@XmlElement(required = true)
	protected DateInfoV2 departureDate;
	protected String equipment;
	protected Integer delayMinutes;
	protected double bearing;
	protected Double heading;
	protected FlightTrackV2.Positions positions;
	protected FlightTrackV2.Waypoints waypoints;
	protected String legacyRoute;
	protected FlightTrackV2.IrregularOperations irregularOperations;

	/**
	 * Gets the value of the flightId property.
	 * 
	 */
	public long getFlightId() {
		return flightId;
	}

	/**
	 * Sets the value of the flightId property.
	 * 
	 */
	public void setFlightId(long value) {
		this.flightId = value;
	}

	/**
	 * Gets the value of the carrier property.
	 * 
	 * @return possible object is {@link AirlineV1 }
	 * 
	 */
	public AirlineV1 getCarrier() {
		return carrier;
	}

	/**
	 * Sets the value of the carrier property.
	 * 
	 * @param value
	 *            allowed object is {@link AirlineV1 }
	 * 
	 */
	public void setCarrier(AirlineV1 value) {
		this.carrier = value;
	}

	/**
	 * Gets the value of the carrierFsCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCarrierFsCode() {
		return carrierFsCode;
	}

	/**
	 * Sets the value of the carrierFsCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCarrierFsCode(String value) {
		this.carrierFsCode = value;
	}

	/**
	 * Gets the value of the flightNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFlightNumber() {
		return flightNumber;
	}

	/**
	 * Sets the value of the flightNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFlightNumber(String value) {
		this.flightNumber = value;
	}

	/**
	 * Gets the value of the tailNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTailNumber() {
		return tailNumber;
	}

	/**
	 * Sets the value of the tailNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTailNumber(String value) {
		this.tailNumber = value;
	}

	/**
	 * Gets the value of the callsign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCallsign() {
		return callsign;
	}

	/**
	 * Sets the value of the callsign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCallsign(String value) {
		this.callsign = value;
	}

	/**
	 * Gets the value of the departureAirport property.
	 * 
	 * @return possible object is {@link AirportV1 }
	 * 
	 */
	public AirportV1 getDepartureAirport() {
		return departureAirport;
	}

	/**
	 * Sets the value of the departureAirport property.
	 * 
	 * @param value
	 *            allowed object is {@link AirportV1 }
	 * 
	 */
	public void setDepartureAirport(AirportV1 value) {
		this.departureAirport = value;
	}

	/**
	 * Gets the value of the departureAirportFsCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepartureAirportFsCode() {
		return departureAirportFsCode;
	}

	/**
	 * Sets the value of the departureAirportFsCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepartureAirportFsCode(String value) {
		this.departureAirportFsCode = value;
	}

	/**
	 * Gets the value of the arrivalAirport property.
	 * 
	 * @return possible object is {@link AirportV1 }
	 * 
	 */
	public AirportV1 getArrivalAirport() {
		return arrivalAirport;
	}

	/**
	 * Sets the value of the arrivalAirport property.
	 * 
	 * @param value
	 *            allowed object is {@link AirportV1 }
	 * 
	 */
	public void setArrivalAirport(AirportV1 value) {
		this.arrivalAirport = value;
	}

	/**
	 * Gets the value of the arrivalAirportFsCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArrivalAirportFsCode() {
		return arrivalAirportFsCode;
	}

	/**
	 * Sets the value of the arrivalAirportFsCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArrivalAirportFsCode(String value) {
		this.arrivalAirportFsCode = value;
	}

	/**
	 * Gets the value of the departureDate property.
	 * 
	 * @return possible object is {@link DateInfoV2 }
	 * 
	 */
	public DateInfoV2 getDepartureDate() {
		return departureDate;
	}

	/**
	 * Sets the value of the departureDate property.
	 * 
	 * @param value
	 *            allowed object is {@link DateInfoV2 }
	 * 
	 */
	public void setDepartureDate(DateInfoV2 value) {
		this.departureDate = value;
	}

	/**
	 * Gets the value of the equipment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEquipment() {
		return equipment;
	}

	/**
	 * Sets the value of the equipment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEquipment(String value) {
		this.equipment = value;
	}

	/**
	 * Gets the value of the delayMinutes property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getDelayMinutes() {
		return delayMinutes;
	}

	/**
	 * Sets the value of the delayMinutes property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setDelayMinutes(Integer value) {
		this.delayMinutes = value;
	}

	/**
	 * Gets the value of the bearing property.
	 * 
	 */
	public double getBearing() {
		return bearing;
	}

	/**
	 * Sets the value of the bearing property.
	 * 
	 */
	public void setBearing(double value) {
		this.bearing = value;
	}

	/**
	 * Gets the value of the heading property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getHeading() {
		return heading;
	}

	/**
	 * Sets the value of the heading property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setHeading(Double value) {
		this.heading = value;
	}

	/**
	 * Gets the value of the positions property.
	 * 
	 * @return possible object is {@link FlightTrackV2 .Positions }
	 * 
	 */
	public FlightTrackV2.Positions getPositions() {
		return positions;
	}

	/**
	 * Sets the value of the positions property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightTrackV2 .Positions }
	 * 
	 */
	public void setPositions(FlightTrackV2.Positions value) {
		this.positions = value;
	}

	/**
	 * Gets the value of the waypoints property.
	 * 
	 * @return possible object is {@link FlightTrackV2 .Waypoints }
	 * 
	 */
	public FlightTrackV2.Waypoints getWaypoints() {
		return waypoints;
	}

	/**
	 * Sets the value of the waypoints property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightTrackV2 .Waypoints }
	 * 
	 */
	public void setWaypoints(FlightTrackV2.Waypoints value) {
		this.waypoints = value;
	}

	/**
	 * Gets the value of the legacyRoute property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLegacyRoute() {
		return legacyRoute;
	}

	/**
	 * Sets the value of the legacyRoute property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLegacyRoute(String value) {
		this.legacyRoute = value;
	}

	/**
	 * Gets the value of the irregularOperations property.
	 * 
	 * @return possible object is {@link FlightTrackV2 .IrregularOperations }
	 * 
	 */
	public FlightTrackV2.IrregularOperations getIrregularOperations() {
		return irregularOperations;
	}

	/**
	 * Sets the value of the irregularOperations property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightTrackV2 .IrregularOperations }
	 * 
	 */
	public void setIrregularOperations(FlightTrackV2.IrregularOperations value) {
		this.irregularOperations = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="irregularOperation" type="{}irregularOperationV2" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "irregularOperation" })
	public static class IrregularOperations {

		protected List<IrregularOperationV2> irregularOperation;

		/**
		 * Gets the value of the irregularOperation property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the irregularOperation property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getIrregularOperation().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link IrregularOperationV2 }
		 * 
		 * 
		 */
		public List<IrregularOperationV2> getIrregularOperation() {
			if (irregularOperation == null) {
				irregularOperation = new ArrayList<IrregularOperationV2>();
			}
			return this.irregularOperation;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="position" type="{}positionV2" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "position" })
	public static class Positions {

		@XmlElement(required = true)
		protected List<PositionV2> position;

		/**
		 * Gets the value of the position property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the position property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPosition().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link PositionV2 }
		 * 
		 * 
		 */
		public List<PositionV2> getPosition() {
			if (position == null) {
				position = new ArrayList<PositionV2>();
			}
			return this.position;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="waypoint" type="{}waypointV2" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "waypoint" })
	public static class Waypoints {

		protected List<WaypointV2> waypoint;

		/**
		 * Gets the value of the waypoint property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the waypoint property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getWaypoint().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link WaypointV2 }
		 * 
		 * 
		 */
		public List<WaypointV2> getWaypoint() {
			if (waypoint == null) {
				waypoint = new ArrayList<WaypointV2>();
			}
			return this.waypoint;
		}

	}

}
