//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for flightStatusExtendedV2 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="flightStatusExtendedV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}flightStatus"/>
 *         &lt;element ref="{}flightStatusExtendedInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightStatusExtendedV2", propOrder = { "flightStatus", "flightStatusExtendedInfo" })
@ToString
public class FlightStatusExtendedV2 {

	@XmlElement(required = true)
	protected FlightStatusV2 flightStatus;
	@XmlElement(required = true)
	protected FlightStatusExtendedInfoV2 flightStatusExtendedInfo;

	/**
	 * Gets the value of the flightStatus property.
	 * 
	 * @return possible object is {@link FlightStatusV2 }
	 * 
	 */
	public FlightStatusV2 getFlightStatus() {
		return flightStatus;
	}

	/**
	 * Sets the value of the flightStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightStatusV2 }
	 * 
	 */
	public void setFlightStatus(FlightStatusV2 value) {
		this.flightStatus = value;
	}

	/**
	 * Gets the value of the flightStatusExtendedInfo property.
	 * 
	 * @return possible object is {@link FlightStatusExtendedInfoV2 }
	 * 
	 */
	public FlightStatusExtendedInfoV2 getFlightStatusExtendedInfo() {
		return flightStatusExtendedInfo;
	}

	/**
	 * Sets the value of the flightStatusExtendedInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightStatusExtendedInfoV2 }
	 * 
	 */
	public void setFlightStatusExtendedInfo(FlightStatusExtendedInfoV2 value) {
		this.flightStatusExtendedInfo = value;
	}

}
