//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for flightTrackResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="flightTrackResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}responseImpl">
 *       &lt;sequence>
 *         &lt;element ref="{}flightTrack" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightTrackResponse", propOrder = { "flightTrack" })
@XmlSeeAlso({ ResponseFlightTrackById.class })
@ToString
public abstract class FlightTrackResponse extends ResponseImpl {

	protected FlightTrackV2 flightTrack;

	/**
	 * Gets the value of the flightTrack property.
	 * 
	 * @return possible object is {@link FlightTrackV2 }
	 * 
	 */
	public FlightTrackV2 getFlightTrack() {
		return flightTrack;
	}

	/**
	 * Sets the value of the flightTrack property.
	 * 
	 * @param value
	 *            allowed object is {@link FlightTrackV2 }
	 * 
	 */
	public void setFlightTrack(FlightTrackV2 value) {
		this.flightTrack = value;
	}

}
