//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for flightStatusExtendedsResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="flightStatusExtendedsResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}responseImpl">
 *       &lt;sequence>
 *         &lt;element ref="{}request" minOccurs="0"/>
 *         &lt;element name="flightStatusExtendeds" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}flightStatusExtended" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightStatusExtendedsResponse", propOrder = { "request", "flightStatusExtendeds" })
@ToString
public class FlightStatusExtendedsResponse extends ResponseImpl {

	@XmlElement(nillable = true)
	protected Object request;
	protected FlightStatusExtendedsResponse.FlightStatusExtendeds flightStatusExtendeds;

	/**
	 * Gets the value of the request property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getRequest() {
		return request;
	}

	/**
	 * Sets the value of the request property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setRequest(Object value) {
		this.request = value;
	}

	/**
	 * Gets the value of the flightStatusExtendeds property.
	 * 
	 * @return possible object is
	 *         {@link FlightStatusExtendedsResponse.FlightStatusExtendeds }
	 * 
	 */
	public FlightStatusExtendedsResponse.FlightStatusExtendeds getFlightStatusExtendeds() {
		return flightStatusExtendeds;
	}

	/**
	 * Sets the value of the flightStatusExtendeds property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link FlightStatusExtendedsResponse.FlightStatusExtendeds }
	 * 
	 */
	public void setFlightStatusExtendeds(FlightStatusExtendedsResponse.FlightStatusExtendeds value) {
		this.flightStatusExtendeds = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element ref="{}flightStatusExtended" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "flightStatusExtended" })
	public static class FlightStatusExtendeds {

		protected List<FlightStatusExtendedV2> flightStatusExtended;

		/**
		 * Gets the value of the flightStatusExtended property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the flightStatusExtended property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFlightStatusExtended().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link FlightStatusExtendedV2 }
		 * 
		 * 
		 */
		public List<FlightStatusExtendedV2> getFlightStatusExtended() {
			if (flightStatusExtended == null) {
				flightStatusExtended = new ArrayList<FlightStatusExtendedV2>();
			}
			return this.flightStatusExtended;
		}

	}

}
