//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import lombok.ToString;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
@ToString
public class ObjectFactory {

	private final static QName _Flightpositionsresponse_QNAME = new QName("", "flightpositionsresponse");
	private final static QName _Flighttracksresponse_QNAME = new QName("", "flighttracksresponse");
	private final static QName _Request_QNAME = new QName("", "request");
	private final static QName _Appendix_QNAME = new QName("", "appendix");
	private final static QName _Equipment_QNAME = new QName("", "equipment");
	private final static QName _FlightStatus_QNAME = new QName("", "flightStatus");
	private final static QName _FlightStatusExtended_QNAME = new QName("", "flightStatusExtended");
	private final static QName _Flightstatusresponse_QNAME = new QName("", "flightstatusresponse");
	private final static QName _Airport_QNAME = new QName("", "airport");
	private final static QName _FlightDistance_QNAME = new QName("", "flightDistance");
	private final static QName _FlightTrack_QNAME = new QName("", "flightTrack");
	private final static QName _ApiResponseError_QNAME = new QName("", "apiResponseError");
	private final static QName _FlightPosition_QNAME = new QName("", "flightPosition");
	private final static QName _Requestbase_QNAME = new QName("", "requestbase");
	private final static QName _Responseimpl_QNAME = new QName("", "responseimpl");
	private final static QName _FlightStatusExtendedInfo_QNAME = new QName("", "flightStatusExtendedInfo");
	private final static QName _Response_QNAME = new QName("", "response");
	private final static QName _Flighttrackresponse_QNAME = new QName("", "flighttrackresponse");
	private final static QName _Airline_QNAME = new QName("", "airline");
	private final static QName _ConfirmedIncident_QNAME = new QName("", "confirmedIncident");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link FlightStatusExtendedsResponse }
	 * 
	 */
	public FlightStatusExtendedsResponse createFlightStatusExtendedsResponse() {
		return new FlightStatusExtendedsResponse();
	}

	/**
	 * Create an instance of {@link ScheduleDataV2 }
	 * 
	 */
	public ScheduleDataV2 createScheduleDataV2() {
		return new ScheduleDataV2();
	}

	/**
	 * Create an instance of {@link FlightStatusUpdateV2 }
	 * 
	 */
	public FlightStatusUpdateV2 createFlightStatusUpdateV2() {
		return new FlightStatusUpdateV2();
	}

	/**
	 * Create an instance of {@link FlightPositionV2 }
	 * 
	 */
	public FlightPositionV2 createFlightPositionV2() {
		return new FlightPositionV2();
	}

	/**
	 * Create an instance of {@link FlightTrackV2 }
	 * 
	 */
	public FlightTrackV2 createFlightTrackV2() {
		return new FlightTrackV2();
	}

	/**
	 * Create an instance of {@link FlightStatusV2 }
	 * 
	 */
	public FlightStatusV2 createFlightStatusV2() {
		return new FlightStatusV2();
	}

	/**
	 * Create an instance of {@link Appendices }
	 * 
	 */
	public Appendices createAppendices() {
		return new Appendices();
	}

	/**
	 * Create an instance of {@link EquipmentV1 }
	 * 
	 */
	public EquipmentV1 createEquipmentV1() {
		return new EquipmentV1();
	}

	/**
	 * Create an instance of {@link FlightStatusExtendedV2 }
	 * 
	 */
	public FlightStatusExtendedV2 createFlightStatusExtendedV2() {
		return new FlightStatusExtendedV2();
	}

	/**
	 * Create an instance of {@link AirportV1 }
	 * 
	 */
	public AirportV1 createAirportV1() {
		return new AirportV1();
	}

	/**
	 * Create an instance of {@link FlightDistanceV2 }
	 * 
	 */
	public FlightDistanceV2 createFlightDistanceV2() {
		return new FlightDistanceV2();
	}

	/**
	 * Create an instance of {@link ApiResponseError }
	 * 
	 */
	public ApiResponseError createApiResponseError() {
		return new ApiResponseError();
	}

	/**
	 * Create an instance of {@link FlightStatusExtendedInfoV2 }
	 * 
	 */
	public FlightStatusExtendedInfoV2 createFlightStatusExtendedInfoV2() {
		return new FlightStatusExtendedInfoV2();
	}

	/**
	 * Create an instance of {@link AirlineV1 }
	 * 
	 */
	public AirlineV1 createAirlineV1() {
		return new AirlineV1();
	}

	/**
	 * Create an instance of {@link ConfirmedIncident }
	 * 
	 */
	public ConfirmedIncident createConfirmedIncident() {
		return new ConfirmedIncident();
	}

	/**
	 * Create an instance of {@link UplineFlightV2 }
	 * 
	 */
	public UplineFlightV2 createUplineFlightV2() {
		return new UplineFlightV2();
	}

	/**
	 * Create an instance of {@link ResponseFlightTrackById }
	 * 
	 */
	public ResponseFlightTrackById createResponseFlightTrackById() {
		return new ResponseFlightTrackById();
	}

	/**
	 * Create an instance of {@link ResponseFleetStatus }
	 * 
	 */
	public ResponseFleetStatus createResponseFleetStatus() {
		return new ResponseFleetStatus();
	}

	/**
	 * Create an instance of {@link RequestFlightTrackById }
	 * 
	 */
	public RequestFlightTrackById createRequestFlightTrackById() {
		return new RequestFlightTrackById();
	}

	/**
	 * Create an instance of {@link OperationalTimesV2 }
	 * 
	 */
	public OperationalTimesV2 createOperationalTimesV2() {
		return new OperationalTimesV2();
	}

	/**
	 * Create an instance of {@link ResponseAirportTracks }
	 * 
	 */
	public ResponseAirportTracks createResponseAirportTracks() {
		return new ResponseAirportTracks();
	}

	/**
	 * Create an instance of {@link ResponseAirportStatus }
	 * 
	 */
	public ResponseAirportStatus createResponseAirportStatus() {
		return new ResponseAirportStatus();
	}

	/**
	 * Create an instance of {@link RequestFlightStatusExtended }
	 * 
	 */
	public RequestFlightStatusExtended createRequestFlightStatusExtended() {
		return new RequestFlightStatusExtended();
	}

	/**
	 * Create an instance of {@link RequestedLongList }
	 * 
	 */
	public RequestedLongList createRequestedLongList() {
		return new RequestedLongList();
	}

	/**
	 * Create an instance of {@link RequestedFlightNumber }
	 * 
	 */
	public RequestedFlightNumber createRequestedFlightNumber() {
		return new RequestedFlightNumber();
	}

	/**
	 * Create an instance of {@link RequestedBoolean }
	 * 
	 */
	public RequestedBoolean createRequestedBoolean() {
		return new RequestedBoolean();
	}

	/**
	 * Create an instance of {@link RequestFlightStatusById }
	 * 
	 */
	public RequestFlightStatusById createRequestFlightStatusById() {
		return new RequestFlightStatusById();
	}

	/**
	 * Create an instance of {@link RequestFleetStatus }
	 * 
	 */
	public RequestFleetStatus createRequestFleetStatus() {
		return new RequestFleetStatus();
	}

	/**
	 * Create an instance of {@link RequestedInteger }
	 * 
	 */
	public RequestedInteger createRequestedInteger() {
		return new RequestedInteger();
	}

	/**
	 * Create an instance of {@link FlightDurationsV2 }
	 * 
	 */
	public FlightDurationsV2 createFlightDurationsV2() {
		return new FlightDurationsV2();
	}

	/**
	 * Create an instance of {@link FlightEquipmentV2 }
	 * 
	 */
	public FlightEquipmentV2 createFlightEquipmentV2() {
		return new FlightEquipmentV2();
	}

	/**
	 * Create an instance of {@link WaypointV2 }
	 * 
	 */
	public WaypointV2 createWaypointV2() {
		return new WaypointV2();
	}

	/**
	 * Create an instance of {@link FlightStatusUpdatedTextV2 }
	 * 
	 */
	public FlightStatusUpdatedTextV2 createFlightStatusUpdatedTextV2() {
		return new FlightStatusUpdatedTextV2();
	}

	/**
	 * Create an instance of {@link ResponseRouteStatus }
	 * 
	 */
	public ResponseRouteStatus createResponseRouteStatus() {
		return new ResponseRouteStatus();
	}

	/**
	 * Create an instance of {@link RequestedAirportV1 }
	 * 
	 */
	public RequestedAirportV1 createRequestedAirportV1() {
		return new RequestedAirportV1();
	}

	/**
	 * Create an instance of {@link RequestedDouble }
	 * 
	 */
	public RequestedDouble createRequestedDouble() {
		return new RequestedDouble();
	}

	/**
	 * Create an instance of {@link RequestFlightsNearBox }
	 * 
	 */
	public RequestFlightsNearBox createRequestFlightsNearBox() {
		return new RequestFlightsNearBox();
	}

	/**
	 * Create an instance of {@link DelaysV2 }
	 * 
	 */
	public DelaysV2 createDelaysV2() {
		return new DelaysV2();
	}

	/**
	 * Create an instance of {@link ResponseFlightsNearRadius }
	 * 
	 */
	public ResponseFlightsNearRadius createResponseFlightsNearRadius() {
		return new ResponseFlightsNearRadius();
	}

	/**
	 * Create an instance of {@link RequestAirportStatus }
	 * 
	 */
	public RequestAirportStatus createRequestAirportStatus() {
		return new RequestAirportStatus();
	}

	/**
	 * Create an instance of {@link DownlineFlightV2 }
	 * 
	 */
	public DownlineFlightV2 createDownlineFlightV2() {
		return new DownlineFlightV2();
	}

	/**
	 * Create an instance of {@link AirportResourcesV2 }
	 * 
	 */
	public AirportResourcesV2 createAirportResourcesV2() {
		return new AirportResourcesV2();
	}

	/**
	 * Create an instance of {@link DateInfoV2 }
	 * 
	 */
	public DateInfoV2 createDateInfoV2() {
		return new DateInfoV2();
	}

	/**
	 * Create an instance of {@link RequestFlightTrack }
	 * 
	 */
	public RequestFlightTrack createRequestFlightTrack() {
		return new RequestFlightTrack();
	}

	/**
	 * Create an instance of {@link PositionV2 }
	 * 
	 */
	public PositionV2 createPositionV2() {
		return new PositionV2();
	}

	/**
	 * Create an instance of {@link ResponseFlightStatus }
	 * 
	 */
	public ResponseFlightStatus createResponseFlightStatus() {
		return new ResponseFlightStatus();
	}

	/**
	 * Create an instance of {@link ResponseFlightTrack }
	 * 
	 */
	public ResponseFlightTrack createResponseFlightTrack() {
		return new ResponseFlightTrack();
	}

	/**
	 * Create an instance of {@link ResponseFleetTrack }
	 * 
	 */
	public ResponseFleetTrack createResponseFleetTrack() {
		return new ResponseFleetTrack();
	}

	/**
	 * Create an instance of {@link IrregularOperationV2 }
	 * 
	 */
	public IrregularOperationV2 createIrregularOperationV2() {
		return new IrregularOperationV2();
	}

	/**
	 * Create an instance of {@link RequestedDate }
	 * 
	 */
	public RequestedDate createRequestedDate() {
		return new RequestedDate();
	}

	/**
	 * Create an instance of {@link RequestedLong }
	 * 
	 */
	public RequestedLong createRequestedLong() {
		return new RequestedLong();
	}

	/**
	 * Create an instance of {@link CodeshareV2 }
	 * 
	 */
	public CodeshareV2 createCodeshareV2() {
		return new CodeshareV2();
	}

	/**
	 * Create an instance of {@link RequestFleetTrack }
	 * 
	 */
	public RequestFleetTrack createRequestFleetTrack() {
		return new RequestFleetTrack();
	}

	/**
	 * Create an instance of {@link ResponseFlightStatusById }
	 * 
	 */
	public ResponseFlightStatusById createResponseFlightStatusById() {
		return new ResponseFlightStatusById();
	}

	/**
	 * Create an instance of {@link RequestFlightsNearRadius }
	 * 
	 */
	public RequestFlightsNearRadius createRequestFlightsNearRadius() {
		return new RequestFlightsNearRadius();
	}

	/**
	 * Create an instance of {@link RequestedString }
	 * 
	 */
	public RequestedString createRequestedString() {
		return new RequestedString();
	}

	/**
	 * Create an instance of {@link RequestFlightStatus }
	 * 
	 */
	public RequestFlightStatus createRequestFlightStatus() {
		return new RequestFlightStatus();
	}

	/**
	 * Create an instance of {@link ResponseFlightsNearBox }
	 * 
	 */
	public ResponseFlightsNearBox createResponseFlightsNearBox() {
		return new ResponseFlightsNearBox();
	}

	/**
	 * Create an instance of {@link RequestAirportTracks }
	 * 
	 */
	public RequestAirportTracks createRequestAirportTracks() {
		return new RequestAirportTracks();
	}

	/**
	 * Create an instance of {@link RequestRouteStatus }
	 * 
	 */
	public RequestRouteStatus createRequestRouteStatus() {
		return new RequestRouteStatus();
	}

	/**
	 * Create an instance of {@link FlightStatusUpdatedDateV2 }
	 * 
	 */
	public FlightStatusUpdatedDateV2 createFlightStatusUpdatedDateV2() {
		return new FlightStatusUpdatedDateV2();
	}

	/**
	 * Create an instance of {@link RequestedAirlineV1 }
	 * 
	 */
	public RequestedAirlineV1 createRequestedAirlineV1() {
		return new RequestedAirlineV1();
	}

	/**
	 * Create an instance of {@link FlightPositionResponse.FlightPositions }
	 * 
	 */
	public FlightPositionResponse.FlightPositions createFlightPositionResponseFlightPositions() {
		return new FlightPositionResponse.FlightPositions();
	}

	/**
	 * Create an instance of
	 * {@link generated.FlightStatusesResponse.FlightStatuses }
	 * 
	 */
	public FlightStatusesResponse.FlightStatuses createFlightStatusesResponseFlightStatuses() {
		return new FlightStatusesResponse.FlightStatuses();
	}

	/**
	 * Create an instance of {@link FlightTracksResponse.FlightTracks }
	 * 
	 */
	public FlightTracksResponse.FlightTracks createFlightTracksResponseFlightTracks() {
		return new FlightTracksResponse.FlightTracks();
	}

	/**
	 * Create an instance of
	 * {@link FlightStatusExtendedsResponse.FlightStatusExtendeds }
	 * 
	 */
	public FlightStatusExtendedsResponse.FlightStatusExtendeds createFlightStatusExtendedsResponseFlightStatusExtendeds() {
		return new FlightStatusExtendedsResponse.FlightStatusExtendeds();
	}

	/**
	 * Create an instance of {@link ScheduleDataV2 .Uplines }
	 * 
	 */
	public ScheduleDataV2.Uplines createScheduleDataV2Uplines() {
		return new ScheduleDataV2.Uplines();
	}

	/**
	 * Create an instance of {@link ScheduleDataV2 .Downlines }
	 * 
	 */
	public ScheduleDataV2.Downlines createScheduleDataV2Downlines() {
		return new ScheduleDataV2.Downlines();
	}

	/**
	 * Create an instance of {@link FlightStatusUpdateV2 .UpdatedTextFields }
	 * 
	 */
	public FlightStatusUpdateV2.UpdatedTextFields createFlightStatusUpdateV2UpdatedTextFields() {
		return new FlightStatusUpdateV2.UpdatedTextFields();
	}

	/**
	 * Create an instance of {@link FlightStatusUpdateV2 .UpdatedDateFields }
	 * 
	 */
	public FlightStatusUpdateV2.UpdatedDateFields createFlightStatusUpdateV2UpdatedDateFields() {
		return new FlightStatusUpdateV2.UpdatedDateFields();
	}

	/**
	 * Create an instance of {@link FlightPositionV2 .Positions }
	 * 
	 */
	public FlightPositionV2.Positions createFlightPositionV2Positions() {
		return new FlightPositionV2.Positions();
	}

	/**
	 * Create an instance of {@link FlightTrackV2 .Positions }
	 * 
	 */
	public FlightTrackV2.Positions createFlightTrackV2Positions() {
		return new FlightTrackV2.Positions();
	}

	/**
	 * Create an instance of {@link FlightTrackV2 .Waypoints }
	 * 
	 */
	public FlightTrackV2.Waypoints createFlightTrackV2Waypoints() {
		return new FlightTrackV2.Waypoints();
	}

	/**
	 * Create an instance of {@link FlightTrackV2 .IrregularOperations }
	 * 
	 */
	public FlightTrackV2.IrregularOperations createFlightTrackV2IrregularOperations() {
		return new FlightTrackV2.IrregularOperations();
	}

	/**
	 * Create an instance of {@link FlightStatusV2 .Codeshares }
	 * 
	 */
	public FlightStatusV2.Codeshares createFlightStatusV2Codeshares() {
		return new FlightStatusV2.Codeshares();
	}

	/**
	 * Create an instance of {@link FlightStatusV2 .FlightStatusUpdates }
	 * 
	 */
	public FlightStatusV2.FlightStatusUpdates createFlightStatusV2FlightStatusUpdates() {
		return new FlightStatusV2.FlightStatusUpdates();
	}

	/**
	 * Create an instance of {@link FlightStatusV2 .IrregularOperations }
	 * 
	 */
	public FlightStatusV2.IrregularOperations createFlightStatusV2IrregularOperations() {
		return new FlightStatusV2.IrregularOperations();
	}

	/**
	 * Create an instance of {@link Appendices.Airlines }
	 * 
	 */
	public Appendices.Airlines createAppendicesAirlines() {
		return new Appendices.Airlines();
	}

	/**
	 * Create an instance of {@link Appendices.Airports }
	 * 
	 */
	public Appendices.Airports createAppendicesAirports() {
		return new Appendices.Airports();
	}

	/**
	 * Create an instance of {@link Appendices.Equipments }
	 * 
	 */
	public Appendices.Equipments createAppendicesEquipments() {
		return new Appendices.Equipments();
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link FlightPositionResponse }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightpositionsresponse")
	public JAXBElement<FlightPositionResponse> createFlightpositionsresponse(FlightPositionResponse value) {
		return new JAXBElement<FlightPositionResponse>(_Flightpositionsresponse_QNAME, FlightPositionResponse.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link FlightTracksResponse }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flighttracksresponse")
	public JAXBElement<FlightTracksResponse> createFlighttracksresponse(FlightTracksResponse value) {
		return new JAXBElement<FlightTracksResponse>(_Flighttracksresponse_QNAME, FlightTracksResponse.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "request")
	public JAXBElement<Object> createRequest(Object value) {
		return new JAXBElement<Object>(_Request_QNAME, Object.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Appendices
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "appendix")
	public JAXBElement<Appendices> createAppendix(Appendices value) {
		return new JAXBElement<Appendices>(_Appendix_QNAME, Appendices.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EquipmentV1
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "equipment")
	public JAXBElement<EquipmentV1> createEquipment(EquipmentV1 value) {
		return new JAXBElement<EquipmentV1>(_Equipment_QNAME, EquipmentV1.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FlightStatusV2
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightStatus")
	public JAXBElement<FlightStatusV2> createFlightStatus(FlightStatusV2 value) {
		return new JAXBElement<FlightStatusV2>(_FlightStatus_QNAME, FlightStatusV2.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link FlightStatusExtendedV2 }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightStatusExtended")
	public JAXBElement<FlightStatusExtendedV2> createFlightStatusExtended(FlightStatusExtendedV2 value) {
		return new JAXBElement<FlightStatusExtendedV2>(_FlightStatusExtended_QNAME, FlightStatusExtendedV2.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightstatusresponse")
	public JAXBElement<Object> createFlightstatusresponse(Object value) {
		return new JAXBElement<Object>(_Flightstatusresponse_QNAME, Object.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AirportV1
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "airport")
	public JAXBElement<AirportV1> createAirport(AirportV1 value) {
		return new JAXBElement<AirportV1>(_Airport_QNAME, AirportV1.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FlightDistanceV2
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightDistance")
	public JAXBElement<FlightDistanceV2> createFlightDistance(FlightDistanceV2 value) {
		return new JAXBElement<FlightDistanceV2>(_FlightDistance_QNAME, FlightDistanceV2.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FlightTrackV2
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightTrack")
	public JAXBElement<FlightTrackV2> createFlightTrack(FlightTrackV2 value) {
		return new JAXBElement<FlightTrackV2>(_FlightTrack_QNAME, FlightTrackV2.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ApiResponseError
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "apiResponseError")
	public JAXBElement<ApiResponseError> createApiResponseError(ApiResponseError value) {
		return new JAXBElement<ApiResponseError>(_ApiResponseError_QNAME, ApiResponseError.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FlightPositionV2
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightPosition")
	public JAXBElement<FlightPositionV2> createFlightPosition(FlightPositionV2 value) {
		return new JAXBElement<FlightPositionV2>(_FlightPosition_QNAME, FlightPositionV2.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RequestBase
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "requestbase")
	public JAXBElement<RequestBase> createRequestbase(RequestBase value) {
		return new JAXBElement<RequestBase>(_Requestbase_QNAME, RequestBase.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ResponseImpl
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "responseimpl")
	public JAXBElement<ResponseImpl> createResponseimpl(ResponseImpl value) {
		return new JAXBElement<ResponseImpl>(_Responseimpl_QNAME, ResponseImpl.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link FlightStatusExtendedInfoV2 }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flightStatusExtendedInfo")
	public JAXBElement<FlightStatusExtendedInfoV2> createFlightStatusExtendedInfo(FlightStatusExtendedInfoV2 value) {
		return new JAXBElement<FlightStatusExtendedInfoV2>(_FlightStatusExtendedInfo_QNAME,
				FlightStatusExtendedInfoV2.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "response")
	public JAXBElement<Object> createResponse(Object value) {
		return new JAXBElement<Object>(_Response_QNAME, Object.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FlightTrackResponse
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "flighttrackresponse")
	public JAXBElement<FlightTrackResponse> createFlighttrackresponse(FlightTrackResponse value) {
		return new JAXBElement<FlightTrackResponse>(_Flighttrackresponse_QNAME, FlightTrackResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AirlineV1
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "airline")
	public JAXBElement<AirlineV1> createAirline(AirlineV1 value) {
		return new JAXBElement<AirlineV1>(_Airline_QNAME, AirlineV1.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmedIncident
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "confirmedIncident")
	public JAXBElement<ConfirmedIncident> createConfirmedIncident(ConfirmedIncident value) {
		return new JAXBElement<ConfirmedIncident>(_ConfirmedIncident_QNAME, ConfirmedIncident.class, null, value);
	}

}
