//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//


package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestFleetTrack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestFleetTrack">
 *   &lt;complexContent>
 *     &lt;extension base="{}requestBase">
 *       &lt;sequence>
 *         &lt;element name="airline" type="{}requestedAirlineV1" minOccurs="0"/>
 *         &lt;element name="airport" type="{}requestedAirportV1" minOccurs="0"/>
 *         &lt;element name="codeshares" type="{}requestedBoolean" minOccurs="0"/>
 *         &lt;element name="includeFlightPlan" type="{}requestedBoolean" minOccurs="0"/>
 *         &lt;element name="maxPositions" type="{}requestedInteger" minOccurs="0"/>
 *         &lt;element name="maxPositionAgeMinutes" type="{}requestedInteger" minOccurs="0"/>
 *         &lt;element name="codeType" type="{}requestedString" minOccurs="0"/>
 *         &lt;element name="maxFlights" type="{}requestedInteger" minOccurs="0"/>
 *         &lt;element name="extendedOptions" type="{}requestedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestFleetTrack", propOrder = {
    "airline",
    "airport",
    "codeshares",
    "includeFlightPlan",
    "maxPositions",
    "maxPositionAgeMinutes",
    "codeType",
    "maxFlights",
    "extendedOptions"
})
public class RequestFleetTrack
    extends RequestBase
{

    protected RequestedAirlineV1 airline;
    protected RequestedAirportV1 airport;
    protected RequestedBoolean codeshares;
    protected RequestedBoolean includeFlightPlan;
    protected RequestedInteger maxPositions;
    protected RequestedInteger maxPositionAgeMinutes;
    protected RequestedString codeType;
    protected RequestedInteger maxFlights;
    protected RequestedString extendedOptions;

    /**
     * Gets the value of the airline property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedAirlineV1 }
     *     
     */
    public RequestedAirlineV1 getAirline() {
        return airline;
    }

    /**
     * Sets the value of the airline property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedAirlineV1 }
     *     
     */
    public void setAirline(RequestedAirlineV1 value) {
        this.airline = value;
    }

    /**
     * Gets the value of the airport property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedAirportV1 }
     *     
     */
    public RequestedAirportV1 getAirport() {
        return airport;
    }

    /**
     * Sets the value of the airport property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedAirportV1 }
     *     
     */
    public void setAirport(RequestedAirportV1 value) {
        this.airport = value;
    }

    /**
     * Gets the value of the codeshares property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedBoolean }
     *     
     */
    public RequestedBoolean getCodeshares() {
        return codeshares;
    }

    /**
     * Sets the value of the codeshares property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedBoolean }
     *     
     */
    public void setCodeshares(RequestedBoolean value) {
        this.codeshares = value;
    }

    /**
     * Gets the value of the includeFlightPlan property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedBoolean }
     *     
     */
    public RequestedBoolean getIncludeFlightPlan() {
        return includeFlightPlan;
    }

    /**
     * Sets the value of the includeFlightPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedBoolean }
     *     
     */
    public void setIncludeFlightPlan(RequestedBoolean value) {
        this.includeFlightPlan = value;
    }

    /**
     * Gets the value of the maxPositions property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedInteger }
     *     
     */
    public RequestedInteger getMaxPositions() {
        return maxPositions;
    }

    /**
     * Sets the value of the maxPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedInteger }
     *     
     */
    public void setMaxPositions(RequestedInteger value) {
        this.maxPositions = value;
    }

    /**
     * Gets the value of the maxPositionAgeMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedInteger }
     *     
     */
    public RequestedInteger getMaxPositionAgeMinutes() {
        return maxPositionAgeMinutes;
    }

    /**
     * Sets the value of the maxPositionAgeMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedInteger }
     *     
     */
    public void setMaxPositionAgeMinutes(RequestedInteger value) {
        this.maxPositionAgeMinutes = value;
    }

    /**
     * Gets the value of the codeType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedString }
     *     
     */
    public RequestedString getCodeType() {
        return codeType;
    }

    /**
     * Sets the value of the codeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedString }
     *     
     */
    public void setCodeType(RequestedString value) {
        this.codeType = value;
    }

    /**
     * Gets the value of the maxFlights property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedInteger }
     *     
     */
    public RequestedInteger getMaxFlights() {
        return maxFlights;
    }

    /**
     * Sets the value of the maxFlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedInteger }
     *     
     */
    public void setMaxFlights(RequestedInteger value) {
        this.maxFlights = value;
    }

    /**
     * Gets the value of the extendedOptions property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedString }
     *     
     */
    public RequestedString getExtendedOptions() {
        return extendedOptions;
    }

    /**
     * Sets the value of the extendedOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedString }
     *     
     */
    public void setExtendedOptions(RequestedString value) {
        this.extendedOptions = value;
    }

}
