//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//


package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestFlightStatusExtended complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestFlightStatusExtended">
 *   &lt;complexContent>
 *     &lt;extension base="{}requestBase">
 *       &lt;sequence>
 *         &lt;element name="flightIds" type="{}requestedLongList" minOccurs="0"/>
 *         &lt;element name="extendedOptions" type="{}requestedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestFlightStatusExtended", propOrder = {
    "flightIds",
    "extendedOptions"
})
public class RequestFlightStatusExtended
    extends RequestBase
{

    protected RequestedLongList flightIds;
    protected RequestedString extendedOptions;

    /**
     * Gets the value of the flightIds property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedLongList }
     *     
     */
    public RequestedLongList getFlightIds() {
        return flightIds;
    }

    /**
     * Sets the value of the flightIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedLongList }
     *     
     */
    public void setFlightIds(RequestedLongList value) {
        this.flightIds = value;
    }

    /**
     * Gets the value of the extendedOptions property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedString }
     *     
     */
    public RequestedString getExtendedOptions() {
        return extendedOptions;
    }

    /**
     * Sets the value of the extendedOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedString }
     *     
     */
    public void setExtendedOptions(RequestedString value) {
        this.extendedOptions = value;
    }

}
