//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.26 at 02:59:00 PM IST 
//

package com.flightapi.bind.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for requestFlightTrackById complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="requestFlightTrackById">
 *   &lt;complexContent>
 *     &lt;extension base="{}requestBase">
 *       &lt;sequence>
 *         &lt;element name="flightId" type="{}requestedLong" minOccurs="0"/>
 *         &lt;element name="includeFlightPlan" type="{}requestedBoolean" minOccurs="0"/>
 *         &lt;element name="maxPositions" type="{}requestedInteger" minOccurs="0"/>
 *         &lt;element name="maxPositionAgeMinutes" type="{}requestedInteger" minOccurs="0"/>
 *         &lt;element name="extendedOptions" type="{}requestedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestFlightTrackById", propOrder = { "flightId", "includeFlightPlan", "maxPositions",
		"maxPositionAgeMinutes", "extendedOptions" })
@ToString
public class RequestFlightTrackById extends RequestBase {

	protected RequestedLong flightId;
	protected RequestedBoolean includeFlightPlan;
	protected RequestedInteger maxPositions;
	protected RequestedInteger maxPositionAgeMinutes;
	protected RequestedString extendedOptions;

	/**
	 * Gets the value of the flightId property.
	 * 
	 * @return possible object is {@link RequestedLong }
	 * 
	 */
	public RequestedLong getFlightId() {
		return flightId;
	}

	/**
	 * Sets the value of the flightId property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestedLong }
	 * 
	 */
	public void setFlightId(RequestedLong value) {
		this.flightId = value;
	}

	/**
	 * Gets the value of the includeFlightPlan property.
	 * 
	 * @return possible object is {@link RequestedBoolean }
	 * 
	 */
	public RequestedBoolean getIncludeFlightPlan() {
		return includeFlightPlan;
	}

	/**
	 * Sets the value of the includeFlightPlan property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestedBoolean }
	 * 
	 */
	public void setIncludeFlightPlan(RequestedBoolean value) {
		this.includeFlightPlan = value;
	}

	/**
	 * Gets the value of the maxPositions property.
	 * 
	 * @return possible object is {@link RequestedInteger }
	 * 
	 */
	public RequestedInteger getMaxPositions() {
		return maxPositions;
	}

	/**
	 * Sets the value of the maxPositions property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestedInteger }
	 * 
	 */
	public void setMaxPositions(RequestedInteger value) {
		this.maxPositions = value;
	}

	/**
	 * Gets the value of the maxPositionAgeMinutes property.
	 * 
	 * @return possible object is {@link RequestedInteger }
	 * 
	 */
	public RequestedInteger getMaxPositionAgeMinutes() {
		return maxPositionAgeMinutes;
	}

	/**
	 * Sets the value of the maxPositionAgeMinutes property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestedInteger }
	 * 
	 */
	public void setMaxPositionAgeMinutes(RequestedInteger value) {
		this.maxPositionAgeMinutes = value;
	}

	/**
	 * Gets the value of the extendedOptions property.
	 * 
	 * @return possible object is {@link RequestedString }
	 * 
	 */
	public RequestedString getExtendedOptions() {
		return extendedOptions;
	}

	/**
	 * Sets the value of the extendedOptions property.
	 * 
	 * @param value
	 *            allowed object is {@link RequestedString }
	 * 
	 */
	public void setExtendedOptions(RequestedString value) {
		this.extendedOptions = value;
	}

}
